#Tomcat 10, JDK17을 사용하는 Docker 이미지

# 베이스 이미지 설정
FROM eclipse-temurin:17

# 환경 변수 설정
ENV CATALINA_HOME /usr/local/tomcat

# Tomcat 다운로드 및 압축 해제
RUN wget -q http://apache.mirror.cdnetworks.com/tomcat/tomcat-10/v10.0.14/bin/apache-tomcat-10.0.14.tar.gz -O /tmp/tomcat.tar.gz \
    && tar xzf /tmp/tomcat.tar.gz -C /usr/local \
    && mv /usr/local/apache-tomcat-* $CATALINA_HOME \
    && rm /tmp/tomcat.tar.gz \
    && rm -rf $CATALINA_HOME/webapps/examples $CATALINA_HOME/webapps/docs

# 포트 설정
EXPOSE 8080

# 실행 명령 설정
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
